# Generated by Django 6.0.2 on 2026-03-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejea_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='total_seats',
            field=models.IntegerField(default=14, max_length=2),
        ),
    ]
