# Generated by Django 6.0.2 on 2026-03-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejea_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
