# Generated by Django 6.0.2 on 2026-03-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejea_app', '0002_vehicle_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='total_seats',
            field=models.IntegerField(default=14),
        ),
    ]
