# Generated by Django 6.0.2 on 2026-03-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_passenger',
            field=models.BooleanField(default=False),
        ),
    ]
