# Generated by Django 6.0.2 on 2026-03-17 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_booked',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='locked_at',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seat_number',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='price_per_seat',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='total_seats',
        ),
        migrations.AlterField(
            model_name='seat',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_seats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
